interface ManufacturerIDs {
  id: number;
  company: string;
}

const MANUFACTURERS_LIST: ManufacturerIDs[] = [
  { id: 0x00, company: "[Used for ID Extensions]" },
  { id: 0x01, company: "Sequential Circuits" },
  { id: 0x02, company: "IDP" },
  { id: 0x03, company: "Voyetra Turtle Beach, Inc." },
  { id: 0x04, company: "Moog Music" },
  { id: 0x05, company: "Passport Designs" },
  { id: 0x06, company: "Lexicon Inc." },
  { id: 0x07, company: "Kurzweil / Young Chang" },
  { id: 0x08, company: "Fender" },
  { id: 0x09, company: "MIDI9" },
  { id: 0x0a, company: "AKG Acoustics" },
  { id: 0x0b, company: "Voyce Music" },
  { id: 0x0c, company: "WaveFrame (Timeline)" },
  { id: 0x0d, company: "ADA Signal Processors, Inc." },
  { id: 0x0e, company: "Garfield Electronics" },
  { id: 0x0f, company: "Ensoniq" },
  { id: 0x10, company: "Oberheim" },
  { id: 0x11, company: "Apple" },
  { id: 0x12, company: "Grey Matter Response" },
  { id: 0x13, company: "Digidesign Inc." },
  { id: 0x14, company: "Palmtree Instruments" },
  { id: 0x15, company: "JLCooper Electronics" },
  { id: 0x16, company: "Lowrey Organ Company" },
  { id: 0x17, company: "Adams-Smith" },
  { id: 0x18, company: "E-mu" },
  { id: 0x19, company: "Harmony Systems" },
  { id: 0x1a, company: "ART" },
  { id: 0x1b, company: "Baldwin" },
  { id: 0x1c, company: "Eventide" },
  { id: 0x1d, company: "Inventronics" },
  { id: 0x1e, company: "Key Concepts" },
  { id: 0x1f, company: "Clarity" },
  { id: 0x20, company: "Passac" },
  { id: 0x21, company: "Proel Labs (SIEL)" },
  { id: 0x22, company: "Synthaxe (UK)" },
  { id: 0x23, company: "Stepp" },
  { id: 0x24, company: "Hohner" },
  { id: 0x25, company: "Twister" },
  { id: 0x26, company: "Ketron s.r.l." },
  { id: 0x27, company: "Jellinghaus MS" },
  { id: 0x28, company: "Southworth Music Systems" },
  { id: 0x29, company: "PPG (Germany)" },
  { id: 0x2a, company: "CESYG Ltd." },
  { id: 0x2b, company: "Solid State Logic Organ Systems" },
  { id: 0x2c, company: "Audio Veritrieb-P. Struven" },
  { id: 0x2d, company: "Neve" },
  { id: 0x2e, company: "Soundtracs Ltd." },
  { id: 0x2f, company: "Elka" },
  { id: 0x30, company: "Dynacord" },
  {
    id: 0x31,
    company: "Viscount International Spa (Intercontinental Electronics)",
  },
  { id: 0x32, company: "Drawmer" },
  { id: 0x33, company: "Clavia Digital Instruments" },
  { id: 0x34, company: "Audio Architecture" },
  { id: 0x35, company: "Generalmusic Corp SpA" },
  { id: 0x36, company: "Cheetah Marketing" },
  { id: 0x37, company: "C.T.M." },
  { id: 0x38, company: "Simmons UK" },
  { id: 0x39, company: "Soundcraft Electronics" },
  { id: 0x3a, company: "Steinberg Media Technologies GmbH" },
  { id: 0x3b, company: "Wersi Gmbh" },
  { id: 0x3c, company: "AVAB Niethammer AB" },
  { id: 0x3d, company: "Digigram" },
  { id: 0x3e, company: "Waldorf Electronics GmbH" },
  { id: 0x3f, company: "Quasimidi" },
  { id: 0x40, company: "Kawai Musical Instruments MFG. CO. Ltd" },
  { id: 0x41, company: "Roland Corporation" },
  { id: 0x42, company: "Korg Inc." },
  { id: 0x43, company: "Yamaha Corporation" },
  { id: 0x44, company: "Casio Computer Co. Ltd" },
  { id: 0x46, company: "Kamiya Studio Co. Ltd" },
  { id: 0x47, company: "Akai Electric Co. Ltd." },
  { id: 0x48, company: "Victor Company of Japan, Ltd." },
  { id: 0x4b, company: "Fujitsu Limited" },
  { id: 0x4c, company: "Sony Corporation" },
  { id: 0x4e, company: "Teac Corporation" },
  { id: 0x50, company: "Matsushita Electric Industrial Co., Ltd" },
  { id: 0x51, company: "Fostex Corporation" },
  { id: 0x52, company: "Zoom Corporation" },
  { id: 0x54, company: "Matsushita Communication Industrial Co., Ltd." },
  { id: 0x55, company: "Suzuki Musical Instruments MFG. Co., Ltd." },
  { id: 0x56, company: "Fuji Sound Corporation Ltd." },
  { id: 0x57, company: "Acoustic Technical Laboratory, Inc." },
  { id: 0x59, company: "Faith, Inc." },
  { id: 0x5a, company: "Internet Corporation" },
  { id: 0x5c, company: "Seekers Co. Ltd." },
  { id: 0x5f, company: "SD Card Association" },
];

export default MANUFACTURERS_LIST;
